apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: HEAD
    path: charts/prometheus
    helm:
      valueFiles:
        - ../prometheus-values/values.yaml
