spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/jprescott1/home-lab.git
    targetRevision: HEAD
    path: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true