name: Deploy ArgoCD App-of-Apps

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'argocd/**'

# jobs:
#   lint:
#     name: Yamllint

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: yamllint
        uses: ansible-actions/yamllint-action@v0.0.2
        with:
          target: "./argocd/**"

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy ArgoCD App-of-Apps
        run: helm upgrade --install argocd-apps ./argocd -f argocd/values.yaml -n argocd --create-namespace
