name: 'ArgoCD Deploy'

on:
  pull_request:
    types: [closed]
    paths:
      - 'argocd/**'

permissions:
  contents: read

jobs:
  sync:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: argocd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Create app-of-apps
        run: |
         argocd app create argocd-app-of-apps \
          --dest-namespace argocd \
          --dest-server https://kubernetes.default.svc \
          --repo https://github.com/jprescott1/home-lab.git \
          --path argocd \
          --project default \
          --server 127.0.0.1:8080 \
          --insecure

      - name: Sync app-of-apps
        run: argocd app sync apps
