name: Deploy Locally

on:
  push:
    branches:
      - main
    paths:
      - './terraform/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan (Pre-Merge)
        run: terraform plan -input=false
    
      # - name: Terraform Apply (Pre-Merge)
      #  run: terraform apply -auto-approve -input=false