name: 'Terraform Post-Merge'

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    # paths:
    #  - 'terraform/**/*'

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan (Pre-Merge)
        run: terraform plan -input=false

      - name: Terraform Apply (Post-Merge)
        run: terraform apply -auto-approve -input=false
        if: github.event.pull_request.merged == true
  
  destroy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
  