name: 'Terraform Pre-Merge'

on:
  pull_request:
    types: [opened, synchronize]
    # paths:
    #  - 'terraform/**/*'

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan (Pre-Merge)
        run: terraform plan -input=false

      - name: Terraform Apply (Pre-Merge)
        run: terraform apply -auto-approve -input=false
